### ISSUE TITLE
Crashes on alpha 136 upon loading the game

### ISSUE THREAD

**Issue by TheRadioactiveBanana** [Sharlottes/Informatis#61]
![Desktop Screenshot 2022 07 17 - 12 10 19 75](https://user-images.githubusercontent.com/89061718/179387200-6cc75faf-f817-4607-a3fd-3238760abe3e.png)

i dont get it but every time i load the game with this mod, it crashes

build: alpha 136 from github

**Comment by TheRadioactiveBanana** [comment]
Mindustry has crashed. How unfortunate.
Version: alpha build 136
OS: Windows 10 x64 (amd64)
Java Version: 16.0.2
Runtime Available Memory: 4084mb
Cores: 12
Mods: informatis:1.6

java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.Integer (java.lang.Float and java.lang.Integer are in module java.base of loader 'bootstrap')
	at arc.Settings.getInt(Settings.java:367)
	at arc.Settings.getInt(Settings.java:387)
	at informatis.ui.window.WaveWindow.lambda$rebuild$27(WaveWindow.java:132)
	at arc.scene.ui.layout.Table.table(Table.java:264)
	at informatis.ui.window.WaveWindow.lambda$rebuild$28(WaveWindow.java:130)
	at arc.scene.ui.layout.Table.<init>(Table.java:75)
	at informatis.ui.window.WaveWindow.rebuild(WaveWindow.java:128)
	at informatis.ui.window.WaveWindow.build(WaveWindow.java:38)
	at informatis.ui.window.Window.lambda$new$0(Window.java:39)
	at arc.scene.ui.layout.Table.pane(Table.java:301)
	at arc.scene.ui.layout.Table.pane(Table.java:296)
	at informatis.ui.window.Window.<init>(Window.java:36)
	at informatis.ui.window.Window.<init>(Window.java:26)
	at informatis.ui.window.WaveWindow.<init>(WaveWindow.java:30)
	at informatis.ui.window.Windows.load(Windows.java:8)
	at informatis.core.Main.lambda$init$2(Main.java:49)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.ClientLauncher.update(ClientLauncher.java:217)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
crash logs

**Comment by Sharlottes** [comment]
fixed
