### ISSUE TITLE
Still crashes on alpha 137 when loading game

### ISSUE THREAD

**Issue by TheRadioactiveBanana** [Sharlottes/Informatis#63]
Mindustry has crashed. How unfortunate.
Version: alpha build 137
OS: Windows 10 x64 (amd64)
Java Version: 16.0.2
Runtime Available Memory: 4084mb
Cores: 12
Mods: informatis:1.6

java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.Integer (java.lang.Float and java.lang.Integer are in module java.base of loader 'bootstrap')
	at arc.Settings.getInt(Settings.java:367)
	at arc.Settings.getInt(Settings.java:387)
	at informatis.ui.window.WaveWindow.lambda$rebuild$27(WaveWindow.java:132)
	at arc.scene.ui.layout.Table.table(Table.java:264)
	at informatis.ui.window.WaveWindow.lambda$rebuild$28(WaveWindow.java:130)
	at arc.scene.ui.layout.Table.<init>(Table.java:75)
	at informatis.ui.window.WaveWindow.rebuild(WaveWindow.java:128)
	at informatis.ui.window.WaveWindow.build(WaveWindow.java:38)
	at informatis.ui.window.Window.lambda$new$0(Window.java:43)
	at arc.scene.ui.layout.Table.<init>(Table.java:75)
	at informatis.ui.window.Window.<init>(Window.java:40)
	at informatis.ui.window.Window.<init>(Window.java:28)
	at informatis.ui.window.WaveWindow.<init>(WaveWindow.java:30)
	at informatis.ui.window.Windows.load(Windows.java:8)
	at informatis.core.Main.lambda$init$2(Main.java:49)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.ClientLauncher.update(ClientLauncher.java:217)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlAp

	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

crash logs again
	
![Desktop Screenshot 2022 08 24 - 19 18 30 51](https://user-images.githubusercontent.com/89061718/186436141-9e6a67ba-75b0-417f-b021-b98094b969e6.png)
plication.java:54)

**Comment by TheRadioactiveBanana** [comment]
Mindustry has crashed. How unfortunate.
Version: alpha build 137
OS: Windows 10 x64 (amd64)
Java Version: 16.0.2
Runtime Available Memory: 4084mb
Cores: 12
Mods: informatis:1.6

java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.Integer (java.lang.Float and java.lang.Integer are in module java.base of loader 'bootstrap')
	at arc.Settings.getInt(Settings.java:367)
	at arc.Settings.getInt(Settings.java:387)
	at informatis.ui.window.WaveWindow.lambda$rebuild$27(WaveWindow.java:132)
	at arc.scene.ui.layout.Table.table(Table.java:264)
	at informatis.ui.window.WaveWindow.lambda$rebuild$28(WaveWindow.java:130)
	at arc.scene.ui.layout.Table.<init>(Table.java:75)
	at informatis.ui.window.WaveWindow.rebuild(WaveWindow.java:128)
	at informatis.ui.window.WaveWindow.build(WaveWindow.java:38)
	at informatis.ui.window.Window.lambda$new$0(Window.java:43)
	at arc.scene.ui.layout.Table.<init>(Table.java:75)
	at informatis.ui.window.Window.<init>(Window.java:40)
	at informatis.ui.window.Window.<init>(Window.java:28)
	at informatis.ui.window.WaveWindow.<init>(WaveWindow.java:30)
	at informatis.ui.window.Windows.load(Windows.java:8)
	at informatis.core.Main.lambda$init$2(Main.java:49)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.ClientLauncher.update(ClientLauncher.java:217)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
	
crash logs again because i forgot to copy a bit of it

**Comment by TheRadioactiveBanana** [comment]
fixed the issue myself
