### ISSUE TITLE
Crashes on launch in 7.0 Build 144

### ISSUE THREAD

**Issue by CEO-Chair** [Sharlottes/Informatis#72]
```Mindustry has crashed. How unfortunate.
Version: release build 144
OS: Windows 10 x64 (amd64)
Java Version: 11.0.16.1
Runtime Available Memory: 4078mb
Cores: 12
Mods: informatis:1.7

java.lang.NoSuchFieldError: maps
	at informatis.ui.fragments.FragmentManager.init(FragmentManager.java:12)
	at informatis.Informatis.lambda$init$2(Informatis.java:50)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.ClientLauncher.update(ClientLauncher.java:215)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```

**Comment by Mac33299** [comment]
Got the same problem

Version: release build 144.1
OS: Windows 10 x64 (amd64)
Java Version: 1.8.0_351
Runtime Available Memory: 1796mb
Cores: 8
Mods: informatis:1.7

java.lang.NoSuchFieldError: maps
	at informatis.ui.fragments.FragmentManager.init(FragmentManager.java:12)
	at informatis.Informatis.lambda$init$2(Informatis.java:50)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.ClientLauncher.update(ClientLauncher.java:215)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by Sector171** [comment]
Me too(mobile, android)

**Comment by poly-1810** [comment]
ive noticed this too, same issue in crash report

**Comment by CEO-Chair** [comment]
Actually seems to be an issue of the type of the UI.maps field changing.
![image](https://github.com/Sharlottes/Informatis/assets/87276335/68d75fab-802f-4216-8428-c91f98ac4e9a)
A simple recompilation of Informatis should fix this issue.

**Comment by CEO-Chair** [comment]
Also confirmed to happen on 144.1

**Comment by Crazyokd** [comment]
me too build 144.1

**Comment by Sharlottes** [comment]
marge and fixed. the crash has not occurred anymore.
