### ISSUE TITLE
crash after launch at v7.0 build 144.3

### ISSUE THREAD

**Issue by P108a** [Sharlottes/Informatis#74]
Version: release build 144.3
(Foo's Client Version: a39154a, May. 23, 2023 Unstable)
Source: mindustry-antigrief/mindustry-client-v7-builds
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4058mb
Cores: 24
Mods: auto-drill:1, extended-ui:0.77, fooinstaller:1.2.4, informatis:1.7

java.lang.NoSuchFieldError: maps
	at informatis.ui.fragments.FragmentManager.init(FragmentManager.java:12)
	at informatis.Informatis.lambda$init$2(Informatis.java:50)
	at arc.Events.fire(Events.java:90)
	at arc.Events.fire(Events.java:76)
	at mindustry.ClientLauncher.update(ClientLauncher.java:241)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:205)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:193)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:57)

informatis:1.7 crash mindustry, I checked

**Comment by Sharlottes** [comment]
marge and fixed. the crash has not occurred anymore.
