### ISSUE TITLE
Crash caused by conflict 

### ISSUE THREAD

**Issue by Bubik111** [Sharlottes/Informatis#83]
So my mindustry crash at startup and i found out the mod conflicted with Scheme Size.
All of my mod are latest update.
Here's the crash report:
```
Mindustry has crashed. How unfortunate.
Version: release build 145.1
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4084mb
Cores: 12
Mods: informatis:1.8.2, scheme-size:2.7.71

java.lang.RuntimeException: java.lang.NoSuchFieldException: tags
	at arc.util.Reflect.get(Reflect.java:56)
	at arc.util.Reflect.get(Reflect.java:61)
	at informatis.ui.fragments.QuickSchemFragment$2.<init>(QuickSchemFragment.java:59)
	at informatis.ui.fragments.QuickSchemFragment.lambda$setSchemTable$0(QuickSchemFragment.java:56)
	at arc.scene.ui.layout.Collapser.<init>(Collapser.java:20)
	at arc.scene.ui.layout.Table.collapser(Table.java:242)
	at informatis.ui.fragments.QuickSchemFragment.setSchemTable(QuickSchemFragment.java:54)
	at informatis.ui.fragments.QuickSchemFragment.<init>(QuickSchemFragment.java:43)
	at informatis.ui.fragments.FragmentManager.init(FragmentManager.java:21)
	at informatis.Informatis.lambda$init$1(Informatis.java:37)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.ClientLauncher.update(ClientLauncher.java:215)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.NoSuchFieldException: tags
	at java.base/java.lang.Class.getDeclaredField(Unknown Source)
	at arc.util.Reflect.get(Reflect.java:52)
	... 16 more
```

**Comment by Sharlottes** [comment]
I didn't get any startup crashes after installing schem-size and restarting.
can you check with the latest action build?

* https://github.com/Sharlottes/Informatis/actions/runs/5991757785
